# -*- coding: utf-8 -*-
"""EX02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uv7YpKt-KxlT5Vr3RSoPK7OMRB9ROEIi
"""

#Bahare_th#EX02#GuessNumberGame
import random

count = 1
number = random.randint(1,100)
guess = int (input("what is your guess?"))


while guess != number:
  if guess > number:
    count +=1
    print("choose lower")
  else: 
    count +=1
    print("choose greater")
  guess = int (input("what is your guess?"))
  
print("You win!!!")
print("Your Try is", count)
