# -*- coding: utf-8 -*-
"""EX02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uv7YpKt-KxlT5Vr3RSoPK7OMRB9ROEIi
"""

#bahare_th#BMI

weight = float(input("enter your weight(kg): "))
height = float(input("enter your height:(cm) "))

m = height / 100

#formula BMI is Weight / height * height in meter
BMI = weight / (m * m)
if BMI < 18.5:
  print("Underweight")
elif BMI >= 18.5 and BMI <= 24.9:
  print("Normal")
elif BMI >= 25 and BMI <= 29.9:
  print("overweight")
elif BMI >= 30 and BMI <=24.9:
  print("Obese")
elif 35 < BMI:
  print("Extremely Obese")