# -*- coding: utf-8 -*-
"""EX02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uv7YpKt-KxlT5Vr3RSoPK7OMRB9ROEIi
"""
#Bahare_th#EX01#hangmanGame


import random
word_bank = ["tree","bird","ali","bahare","apple","star","computer","python","theory","mashad"]
list_true=''
joon = 6
lives_visual_dict = {
        0: """
                ___________
               | /        | 
               |/        ( )
               |          |
               |         / \\
               |
           """,
        1: """
                ___________
               | /        | 
               |/        ( )
               |          |
               |         / 
               |
            """,
        2: """
                ___________
               | /        | 
               |/        ( )
               |          |
               |          
               |
            """,
        3: """
                ___________
               | /        | 
               |/        ( )
               |          
               |          
               |
            """,
        4: """
                ___________
               | /        | 
               |/        
               |          
               |          
               |
            """,
        5: """
                ___________
               | /        
               |/        
               |          
               |          
               |
            """,
        6: """
               |
               |
               |
               |
               |
            """,
        7: "",
    }

#choice random word                          
word = random.choice(word_bank)
while True:
    
    #print true on underline 
  for i in range(len(word)):
    if word[i] in list_true:
      print(word[i],end="")
    else:
     print("_ ",end ="")
    
    #Enter user char
  word_user = input("\nEnter your char: ").lower()
  if len(word_user) == 1:
    if word_user in word:
      print("afrin")
      list_true += word_user
    else:
      joon -= 1
      print("wrong!!!")
        #print hangman graphic
      print(lives_visual_dict[joon])
  else:
    print("ye harf vared konid!")
    
    #winner conditioning
  if list_true == word: 
    print("great!")
    print(word)
    break
  elif joon == 0:
    print("You are lose,Sorry maby later!")
    break
