# -*- coding: utf-8 -*-
"""EX02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uv7YpKt-KxlT5Vr3RSoPK7OMRB9ROEIi
"""

#bahare_th#KG to Pound
kg =float(input("Enter Kg:"))

pound = kg * 2.205
print(pound)