# -*- coding: utf-8 -*-
"""EX02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uv7YpKt-KxlT5Vr3RSoPK7OMRB9ROEIi
"""

#bahare_th#Ex04#triangel

x = float(input("Enter x:"))
y = float(input("Enter y:"))
z = float(input("Enter z:"))

if x < (z+y):
  print("this is True")
else:
  print("this is false")